// Mock database for size-based filter browsing
import { SizeFilterProduct, CommonSize } from '@/lib/types/size-filter';

// Common filter sizes (most popular)
export const COMMON_SIZES: CommonSize[] = [
  // Air filters - Most popular sizes
  { height: 16, width: 25, depth: 1, label: '16x25x1', popularity: 10, category: 'air' }, // Super common
  { height: 16, width: 20, depth: 1, label: '16x20x1', popularity: 10, category: 'air' },
  { height: 20, width: 20, depth: 1, label: '20x20x1', popularity: 9, category: 'air' },
  { height: 20, width: 25, depth: 1, label: '20x25x1', popularity: 9, category: 'air' },
  { height: 14, width: 20, depth: 1, label: '14x20x1', popularity: 8, category: 'air' },
  { height: 14, width: 25, depth: 1, label: '14x25x1', popularity: 7, category: 'air' },
  { height: 16, width: 24, depth: 1, label: '16x24x1', popularity: 7, category: 'air' },
  { height: 24, width: 24, depth: 1, label: '24x24x1', popularity: 7, category: 'air' },
  { height: 12, width: 24, depth: 1, label: '12x24x1', popularity: 6, category: 'air' },
  { height: 20, width: 30, depth: 1, label: '20x30x1', popularity: 6, category: 'air' },
  
  // 4-inch deep filters (for media air cleaners)
  { height: 16, width: 25, depth: 4, label: '16x25x4', popularity: 6, category: 'air' },
  { height: 20, width: 20, depth: 4, label: '20x20x4', popularity: 5, category: 'air' },
  { height: 16, width: 20, depth: 4, label: '16x20x4', popularity: 5, category: 'air' },
  
  // 2-inch deep filters
  { height: 16, width: 20, depth: 2, label: '16x20x2', popularity: 4, category: 'air' },
  { height: 20, width: 25, depth: 2, label: '20x25x2', popularity: 4, category: 'air' },
];

// Mock product database with size information
export const SIZE_FILTER_PRODUCTS: SizeFilterProduct[] = [
  // 16x20x1 filters
  {
    id: 1001,
    name: '16x20x1 MERV 8 Pleated Air Filter',
    brand: 'Filters Fast',
    sku: 'FF-1620-M8',
    price: 9.99,
    rating: 4.7,
    reviewCount: 1234,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Best Value'],
    dimensions: { height: 16, width: 20, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1002,
    name: '16x20x1 MERV 11 Pleated Air Filter',
    brand: 'Filters Fast',
    sku: 'FF-1620-M11',
    price: 11.99,
    rating: 4.8,
    reviewCount: 2156,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Best Seller'],
    dimensions: { height: 16, width: 20, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1003,
    name: '16x20x1 MERV 13 Allergen Defense Filter',
    brand: 'Filters Fast',
    sku: 'FF-1620-M13',
    price: 14.99,
    originalPrice: 17.99,
    rating: 4.9,
    reviewCount: 3421,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Top Rated', 'Premium'],
    dimensions: { height: 16, width: 20, depth: 1 },
    mervRating: 13,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1004,
    name: '16x20x1 MERV 11 Filter (6-Pack)',
    brand: 'Filters Fast',
    sku: 'FF-1620-M11-6PK',
    price: 59.99,
    originalPrice: 71.94,
    rating: 4.8,
    reviewCount: 892,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Save 17%'],
    dimensions: { height: 16, width: 20, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 6,
  },

  // 16x25x1 filters
  {
    id: 1005,
    name: '16x25x1 MERV 8 Pleated Air Filter',
    brand: 'Filters Fast',
    sku: 'FF-1625-M8',
    price: 10.99,
    rating: 4.7,
    reviewCount: 1567,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 16, width: 25, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1006,
    name: '16x25x1 MERV 11 Pleated Air Filter',
    brand: 'Filters Fast',
    sku: 'FF-1625-M11',
    price: 12.99,
    rating: 4.8,
    reviewCount: 2789,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Best Seller'],
    dimensions: { height: 16, width: 25, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1007,
    name: '16x25x1 MERV 13 Premium Filter',
    brand: 'Filters Fast',
    sku: 'FF-1625-M13',
    price: 15.99,
    rating: 4.9,
    reviewCount: 3912,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Premium', 'Top Rated'],
    dimensions: { height: 16, width: 25, depth: 1 },
    mervRating: 13,
    category: 'air',
    packSize: 1,
  },

  // 20x20x1 filters
  {
    id: 1008,
    name: '20x20x1 MERV 8 Pleated Filter',
    brand: '3M Filtrete',
    sku: '3M-2020-M8',
    price: 11.99,
    rating: 4.7,
    reviewCount: 1823,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 20, width: 20, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1009,
    name: '20x20x1 MERV 11 Allergen Filter',
    brand: 'Filtrete',
    sku: 'FIL-2020-M11',
    price: 13.99,
    rating: 4.8,
    reviewCount: 2934,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Best Value'],
    dimensions: { height: 20, width: 20, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1010,
    name: '20x20x1 MERV 13 Premium Pleated',
    brand: 'Filtrete',
    sku: 'FIL-2020-M13',
    price: 16.99,
    rating: 4.9,
    reviewCount: 4123,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Top Rated'],
    dimensions: { height: 20, width: 20, depth: 1 },
    mervRating: 13,
    category: 'air',
    packSize: 1,
  },

  // 20x25x1 filters
  {
    id: 1011,
    name: '20x25x1 MERV 8 Basic Filter',
    brand: 'Filters Fast',
    sku: 'FF-2025-M8',
    price: 12.99,
    rating: 4.6,
    reviewCount: 1456,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 20, width: 25, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1012,
    name: '20x25x1 MERV 11 Pleated Filter',
    brand: 'Honeywell',
    sku: 'HON-2025-M11',
    price: 14.99,
    rating: 4.8,
    reviewCount: 2567,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 20, width: 25, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1013,
    name: '20x25x1 MERV 13 Allergen Defense',
    brand: 'Filtrete',
    sku: 'FIL-2025-M13',
    price: 17.99,
    rating: 4.9,
    reviewCount: 3789,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Premium'],
    dimensions: { height: 20, width: 25, depth: 1 },
    mervRating: 13,
    category: 'air',
    packSize: 1,
  },

  // 14x20x1 filters
  {
    id: 1014,
    name: '14x20x1 MERV 8 Pleated Air Filter',
    brand: 'Nordic Pure',
    sku: 'NP-1420-M8',
    price: 8.99,
    rating: 4.6,
    reviewCount: 987,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 14, width: 20, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1015,
    name: '14x20x1 MERV 11 Filter',
    brand: 'Filters Fast',
    sku: 'FF-1420-M11',
    price: 10.99,
    rating: 4.7,
    reviewCount: 1678,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 14, width: 20, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1016,
    name: '14x20x1 MERV 13 Premium',
    brand: 'Filters Fast',
    sku: 'FF-1420-M13',
    price: 13.99,
    rating: 4.8,
    reviewCount: 2234,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 14, width: 20, depth: 1 },
    mervRating: 13,
    category: 'air',
    packSize: 1,
  },

  // 24x24x1 filters
  {
    id: 1017,
    name: '24x24x1 MERV 8 Pleated Filter',
    brand: 'Nordic Pure',
    sku: 'NP-2424-M8',
    price: 14.99,
    rating: 4.6,
    reviewCount: 789,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 24, width: 24, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1018,
    name: '24x24x1 MERV 11 Air Filter',
    brand: 'Filters Fast',
    sku: 'FF-2424-M11',
    price: 17.99,
    rating: 4.7,
    reviewCount: 1234,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 24, width: 24, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },

  // 4-inch deep filters
  {
    id: 1019,
    name: '16x25x4 MERV 11 Deep Pleated Filter',
    brand: 'Honeywell',
    sku: 'HON-1625-M11-4',
    price: 24.99,
    rating: 4.8,
    reviewCount: 1456,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 16, width: 25, depth: 4 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1020,
    name: '20x20x4 MERV 13 Media Filter',
    brand: 'Aprilaire',
    sku: 'APR-2020-M13-4',
    price: 32.99,
    rating: 4.9,
    reviewCount: 2345,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    badges: ['Premium'],
    dimensions: { height: 20, width: 20, depth: 4 },
    mervRating: 13,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1021,
    name: '16x20x4 MERV 11 Media Air Cleaner Filter',
    brand: 'Filters Fast',
    sku: 'FF-1620-M11-4',
    price: 22.99,
    rating: 4.8,
    reviewCount: 987,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 16, width: 20, depth: 4 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },

  // 14x25x1 filters
  {
    id: 1022,
    name: '14x25x1 MERV 8 Pleated Filter',
    brand: 'Filters Fast',
    sku: 'FF-1425-M8',
    price: 10.99,
    rating: 4.6,
    reviewCount: 876,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 14, width: 25, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1023,
    name: '14x25x1 MERV 11 Air Filter',
    brand: 'Filters Fast',
    sku: 'FF-1425-M11',
    price: 12.99,
    rating: 4.7,
    reviewCount: 1543,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 14, width: 25, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },

  // 16x24x1 filters
  {
    id: 1024,
    name: '16x24x1 MERV 8 Basic Filter',
    brand: 'Nordic Pure',
    sku: 'NP-1624-M8',
    price: 9.99,
    rating: 4.6,
    reviewCount: 654,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 16, width: 24, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1025,
    name: '16x24x1 MERV 11 Pleated Filter',
    brand: 'Filters Fast',
    sku: 'FF-1624-M11',
    price: 12.99,
    rating: 4.7,
    reviewCount: 1234,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 16, width: 24, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },

  // 20x30x1 filters
  {
    id: 1026,
    name: '20x30x1 MERV 8 Pleated Filter',
    brand: 'Filters Fast',
    sku: 'FF-2030-M8',
    price: 15.99,
    rating: 4.6,
    reviewCount: 543,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 20, width: 30, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1027,
    name: '20x30x1 MERV 11 Air Filter',
    brand: 'Filtrete',
    sku: 'FIL-2030-M11',
    price: 18.99,
    rating: 4.7,
    reviewCount: 876,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 20, width: 30, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },

  // 12x24x1 filters
  {
    id: 1028,
    name: '12x24x1 MERV 8 Pleated Filter',
    brand: 'Filters Fast',
    sku: 'FF-1224-M8',
    price: 8.99,
    rating: 4.6,
    reviewCount: 456,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 12, width: 24, depth: 1 },
    mervRating: 8,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1029,
    name: '12x24x1 MERV 11 Air Filter',
    brand: 'Filters Fast',
    sku: 'FF-1224-M11',
    price: 10.99,
    rating: 4.7,
    reviewCount: 789,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 12, width: 24, depth: 1 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },

  // 2-inch filters
  {
    id: 1030,
    name: '16x20x2 MERV 11 Pleated Filter',
    brand: 'Filters Fast',
    sku: 'FF-1620-M11-2',
    price: 16.99,
    rating: 4.7,
    reviewCount: 567,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 16, width: 20, depth: 2 },
    mervRating: 11,
    category: 'air',
    packSize: 1,
  },
  {
    id: 1031,
    name: '20x25x2 MERV 13 Extended Surface Filter',
    brand: 'Honeywell',
    sku: 'HON-2025-M13-2',
    price: 21.99,
    rating: 4.8,
    reviewCount: 987,
    image: '/images/air-filter-placeholder.jpg',
    inStock: true,
    dimensions: { height: 20, width: 25, depth: 2 },
    mervRating: 13,
    category: 'air',
    packSize: 1,
  },
];

// Get unique dimensions from products
export function getUniqueDimensions(): {
  heights: number[];
  widths: number[];
  depths: number[];
} {
  const heights = [...new Set(SIZE_FILTER_PRODUCTS.map(p => p.dimensions.height))].sort((a, b) => a - b);
  const widths = [...new Set(SIZE_FILTER_PRODUCTS.map(p => p.dimensions.width))].sort((a, b) => a - b);
  const depths = [...new Set(SIZE_FILTER_PRODUCTS.map(p => p.dimensions.depth))].sort((a, b) => a - b);
  
  return { heights, widths, depths };
}

// Get products by exact dimensions
export function getProductsBySize(
  height: number | null,
  width: number | null,
  depth: number | null
): SizeFilterProduct[] {
  return SIZE_FILTER_PRODUCTS.filter(product => {
    if (height !== null && product.dimensions.height !== height) return false;
    if (width !== null && product.dimensions.width !== width) return false;
    if (depth !== null && product.dimensions.depth !== depth) return false;
    return true;
  });
}

// Get count of products for a specific dimension combination
export function getProductCountBySize(
  height: number | null,
  width: number | null,
  depth: number | null
): number {
  return getProductsBySize(height, width, depth).length;
}

